name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r api/requirements.txt
          pip install -r manager/requirements.txt
      - name: Test API
        run: |
          cd api && python -c "import main"
      - name: Test Manager
        run: |
          cd manager && python -c "import auth.jwt_manager"
